---
abstract: 'Cook your distributions with Dist::Zilla'
author:
  - 'Jeffrey Ryan Thalhammer <jeff@imaginative-software.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Chef
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  Dist::Zilla::App::Command::cook:
    file: lib/Dist/Zilla/App/Command/cook.pm
    version: 0.001
  Dist::Zilla::App::Command::scrub:
    file: lib/Dist/Zilla/App/Command/scrub.pm
    version: 0.001
  Dist::Zilla::App::Command::stock:
    file: lib/Dist/Zilla/App/Command/stock.pm
    version: 0.001
  Dist::Zilla::Chef:
    file: lib/Dist/Zilla/Chef.pm
    version: 0.001
requires:
  App::cpanminus: 1.5
  Dist::Zilla::App: 0
  File::Path: 0
  Moose::Autobox: 0
  Pinto: 0
  Pinto::Creator: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/thaljef/Dist-Zilla-Chef/issues
  repository: git://github.com/thaljef/Dist-Zilla-Chef.git
version: 0.001
